# prometheus.yml

global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: fastapi
  honor_labels: true
  static_configs:
  - targets:
    - js-fastapi-monitoring  # metrics from model
    
- job_name: 'jenkins'
  metrics_path: /prometheus/
  static_configs:
    - targets:
      - ec2-54-64-72-114.ap-northeast-1.compute.amazonaws.com:8080